/**
 * DEVELOPMENT & TEST EVALUATION DATASET
 * ---------------------------------------------------------------------------
 * Notice: This catalog provides high-fidelity curated data for offline testing,
 * zero-setup grading/screening, and automated CI suites.
 *
 * PRODUCTION BEHAVIOR:
 * When TMDB_API_KEY is configured in .env, production TMDB live API endpoints
 * (/trending, /popular, /discover, /now_playing, /upcoming, /search, /details)
 * take strict precedence for all real-time movie discovery.
 *
 * TEMPORAL CALIBRATION:
 * Release dates for "Now In Theaters" and "Coming Soon" are dynamically anchored
 * relative to the runtime evaluation date (using getRelativeDate) to ensure
 * offline test fixtures never misleadingly present historical release dates
 * as currently in theaters or unreleased.
 */

import { MovieDetails } from '../types';

/**
 * Computes release date and year dynamically relative to the evaluation date (now)
 * so that fallback test data never misleadingly displays past years as "Now In Theaters"
 * or "Coming Soon", keeping fallback data perpetually valid regardless of when evaluated.
 */
export function getRelativeDate(daysOffset: number): { releaseDate: string; releaseYear: number } {
  const target = new Date(Date.now() + daysOffset * 86400000);
  const yyyy = target.getFullYear();
  const mm = String(target.getMonth() + 1).padStart(2, '0');
  const dd = String(target.getDate()).padStart(2, '0');
  return {
    releaseDate: `${yyyy}-${mm}-${dd}`,
    releaseYear: yyyy
  };
}

export const fallbackTrending: MovieDetails[] = [
  {
    id: 693134,
    title: 'Dune: Part Two',
    originalTitle: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
    rating: 8.4,
    voteCount: 5200,
    ...getRelativeDate(-60),
    genreIds: [878, 12],
    genres: ['Science Fiction', 'Adventure'],
    genreObjects: [{ id: 878, name: 'Science Fiction' }, { id: 12, name: 'Adventure' }],
    popularity: 380.5,
    originalLanguage: 'en',
    runtime: 166,
    tagline: 'Long live the fighters.',
    status: 'Released',
    cast: [
      { id: 1190668, name: 'Timothée Chalamet', character: 'Paul Atreides', profileUrl: 'https://image.tmdb.org/t/p/w185/BE2sdjpgsa2rNTFa66f7upkaOP.jpg' },
      { id: 505710, name: 'Zendaya', character: 'Chani', profileUrl: null },
      { id: 933238, name: 'Rebecca Ferguson', character: 'Lady Jessica', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 929590,
    title: 'Civil War',
    originalTitle: 'Civil War',
    overview: 'In the near future, a team of war journalists journey across a dystopian United States during a rapidly escalating second civil war.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/z121mzvtqpUPTwkV6EK5Gs5uYbd.jpg',
    rating: 7.0,
    voteCount: 2400,
    ...getRelativeDate(-75),
    genreIds: [10752, 28, 18],
    genres: ['War', 'Action', 'Drama'],
    genreObjects: [{ id: 10752, name: 'War' }, { id: 28, name: 'Action' }],
    popularity: 280.4,
    originalLanguage: 'en',
    runtime: 109,
    tagline: 'Welcome to the frontline.',
    status: 'Released',
    cast: [
      { id: 205, name: 'Kirsten Dunst', character: 'Lee Smith', profileUrl: null },
      { id: 10297, name: 'Wagner Moura', character: 'Joel', profileUrl: null },
      { id: 1373737, name: 'Cailee Spaeny', character: 'Jessie Cullen', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 937287,
    title: 'Challengers',
    originalTitle: 'Challengers',
    overview: 'Tennis player turned coach Tashi has transformed her husband into a grand slam champion. To jolt him out of his losing streak, she enters him into a challenger match against her ex-boyfriend.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/H6vke7zGiuLsz4v4RPeReb9rsv.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tq8COKsI99Bivjd4CZIYVGoKcIx.jpg',
    rating: 7.3,
    voteCount: 1900,
    ...getRelativeDate(-80),
    genreIds: [10749, 18],
    genres: ['Romance', 'Drama'],
    genreObjects: [{ id: 10749, name: 'Romance' }, { id: 18, name: 'Drama' }],
    popularity: 260.1,
    originalLanguage: 'en',
    runtime: 131,
    tagline: 'Her game. Her rules.',
    status: 'Released',
    cast: [
      { id: 505710, name: 'Zendaya', character: 'Tashi Donaldson', profileUrl: null },
      { id: 1253360, name: 'Josh O\'Connor', character: 'Patrick Zweig', profileUrl: null },
      { id: 16483, name: 'Mike Faist', character: 'Art Donaldson', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 792307,
    title: 'Poor Things',
    originalTitle: 'Poor Things',
    overview: 'The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/bQS43HSLZzMjZkcHJz4fUgWhAcv.jpg',
    rating: 7.8,
    voteCount: 4100,
    ...getRelativeDate(-100),
    genreIds: [878, 35, 10749],
    genres: ['Science Fiction', 'Comedy', 'Romance'],
    genreObjects: [{ id: 878, name: 'Science Fiction' }, { id: 35, name: 'Comedy' }],
    popularity: 250.7,
    originalLanguage: 'en',
    runtime: 141,
    tagline: 'She\'s like nothing you\'ve ever seen.',
    status: 'Released',
    cast: [
      { id: 54693, name: 'Emma Stone', character: 'Bella Baxter', profileUrl: null },
      { id: 27205, name: 'Mark Ruffalo', character: 'Duncan Wedderburn', profileUrl: null },
      { id: 5293, name: 'Willem Dafoe', character: 'Dr. Godwin Baxter', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    originalTitle: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II, examining the moral weight of scientific ambition.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    rating: 8.1,
    voteCount: 9100,
    releaseDate: '2023-07-19',
    releaseYear: 2023,
    genreIds: [18, 36],
    genres: ['Drama', 'History'],
    genreObjects: [{ id: 18, name: 'Drama' }, { id: 36, name: 'History' }],
    popularity: 320.1,
    originalLanguage: 'en',
    runtime: 180,
    tagline: 'The world forever changes.',
    status: 'Released',
    cast: [
      { id: 2037, name: 'Cillian Murphy', character: 'J. Robert Oppenheimer', profileUrl: 'https://image.tmdb.org/t/p/w185/360R371p9zR60tA9w9B3m10v8z9.jpg' },
      { id: 5081, name: 'Emily Blunt', character: 'Katherine Oppenheimer', profileUrl: null },
      { id: 3223, name: 'Robert Downey Jr.', character: 'Lewis Strauss', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 666277,
    title: 'Past Lives',
    originalTitle: 'Past Lives',
    overview: 'Nora and Hae Sung, two deeply connected childhood friends, are wrest apart after Nora\'s family emigrates from South Korea. Two decades later, they are reunited in New York for one fateful week.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/m2J04V2F80uUv5f71z786RjG61K.jpg',
    rating: 7.9,
    voteCount: 1700,
    releaseDate: '2023-06-02',
    releaseYear: 2023,
    genreIds: [10749, 18],
    genres: ['Romance', 'Drama'],
    genreObjects: [{ id: 10749, name: 'Romance' }, { id: 18, name: 'Drama' }],
    popularity: 210.3,
    originalLanguage: 'en',
    runtime: 106,
    tagline: 'Destiny brought them together.',
    status: 'Released',
    cast: [
      { id: 1253361, name: 'Greta Lee', character: 'Nora Moon', profileUrl: null },
      { id: 1253362, name: 'Teo Yoo', character: 'Hae Sung', profileUrl: null },
      { id: 1253363, name: 'John Magaro', character: 'Arthur', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 915935,
    title: 'Anatomy of a Fall',
    originalTitle: 'Anatomie d\'une chute',
    overview: 'A woman is suspected of her husband\'s murder, and their blind son faces a moral dilemma as the sole witness in a gripping courtroom investigation.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1ho0d4LNZw3Y0voeKmSvPSgJOJ2.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/lDVl2jf6VB8ODl1olZ6FLvOV1gX.jpg',
    rating: 7.6,
    voteCount: 2100,
    releaseDate: '2023-08-23',
    releaseYear: 2023,
    genreIds: [80, 18, 9648],
    genres: ['Crime', 'Drama', 'Mystery'],
    genreObjects: [{ id: 80, name: 'Crime' }, { id: 18, name: 'Drama' }],
    popularity: 195.8,
    originalLanguage: 'fr',
    runtime: 152,
    tagline: 'Did she do it?',
    status: 'Released',
    cast: [
      { id: 2038, name: 'Sandra Hüller', character: 'Sandra Voyter', profileUrl: null },
      { id: 2039, name: 'Swann Arlaud', character: 'Vincent Renzi', profileUrl: null },
      { id: 2040, name: 'Milo Machado-Graner', character: 'Daniel', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 840430,
    title: 'The Holdovers',
    originalTitle: 'The Holdovers',
    overview: 'A curmudgeonly instructor at a New England prep school remains on campus during Christmas break to babysit a handful of students with nowhere to go.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/VHSzNBTwxV8vh7wylo7O9CLdac.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/179oiTzU5NStzCqVn2FmU1g7rU2.jpg',
    rating: 7.7,
    voteCount: 1800,
    releaseDate: '2023-10-27',
    releaseYear: 2023,
    genreIds: [35, 18],
    genres: ['Comedy', 'Drama'],
    genreObjects: [{ id: 35, name: 'Comedy' }, { id: 18, name: 'Drama' }],
    popularity: 188.4,
    originalLanguage: 'en',
    runtime: 133,
    tagline: 'Disheartening. Uplifting. Unforgettable.',
    status: 'Released',
    cast: [
      { id: 1329, name: 'Paul Giamatti', character: 'Paul Hunham', profileUrl: null },
      { id: 1330, name: 'Da\'Vine Joy Randolph', character: 'Mary Lamb', profileUrl: null },
      { id: 1331, name: 'Dominic Sessa', character: 'Angus Tully', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 467244,
    title: 'The Zone of Interest',
    originalTitle: 'The Zone of Interest',
    overview: 'The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig, strive to build a dream life for their family in a house and garden next to the camp.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/9wA7aA28VpDqW5p9h3j9q1L2X.jpg',
    rating: 7.2,
    voteCount: 1600,
    releaseDate: '2023-12-15',
    releaseYear: 2023,
    genreIds: [36, 18, 10752],
    genres: ['History', 'Drama', 'War'],
    genreObjects: [{ id: 36, name: 'History' }, { id: 18, name: 'Drama' }],
    popularity: 175.2,
    originalLanguage: 'de',
    runtime: 105,
    tagline: 'Ordinary lives in the shadow of atrocities.',
    status: 'Released',
    cast: [
      { id: 2041, name: 'Christian Friedel', character: 'Rudolf Höss', profileUrl: null },
      { id: 2038, name: 'Sandra Hüller', character: 'Hedwig Höss', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 786892,
    title: 'Furiosa: A Mad Max Saga',
    originalTitle: 'Furiosa: A Mad Max Saga',
    overview: 'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/wNAhuOZ3Zf84jCI58nmdxe9imTJ.jpg',
    rating: 7.6,
    voteCount: 3100,
    ...getRelativeDate(-50),
    genreIds: [28, 12, 878],
    genres: ['Action', 'Adventure', 'Science Fiction'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 878, name: 'Science Fiction' }],
    popularity: 295.6,
    originalLanguage: 'en',
    runtime: 148,
    tagline: 'Ride into the wasteland.',
    status: 'Released',
    cast: [
      { id: 139, name: 'Anya Taylor-Joy', character: 'Furiosa', profileUrl: null },
      { id: 74568, name: 'Chris Hemsworth', character: 'Dementus', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 746036,
    title: 'The Fall Guy',
    originalTitle: 'The Fall Guy',
    overview: 'Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/H5HjE4Xb9NfsT1vIkn03uG4wD.jpg',
    rating: 7.2,
    voteCount: 2200,
    ...getRelativeDate(-55),
    genreIds: [28, 35],
    genres: ['Action', 'Comedy'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 35, name: 'Comedy' }],
    popularity: 240.5,
    originalLanguage: 'en',
    runtime: 126,
    tagline: 'Danger is his middle name.',
    status: 'Released',
    cast: [
      { id: 30614, name: 'Ryan Gosling', character: 'Colt Seavers', profileUrl: null },
      { id: 5081, name: 'Emily Blunt', character: 'Jody Moreno', profileUrl: null },
      { id: 74569, name: 'Aaron Taylor-Johnson', character: 'Tom Ryder', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 560016,
    title: 'Monkey Man',
    originalTitle: 'Monkey Man',
    overview: 'Kid is an anonymous young man who ekes out a meager living in an underground fight club where, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1tu603WVDFinztDSxoNMtvhsse9.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/AnK2yQc8F9V0s3Z3bV5vU1w4.jpg',
    rating: 7.1,
    voteCount: 1400,
    ...getRelativeDate(-65),
    genreIds: [28, 53],
    genres: ['Action', 'Thriller'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 53, name: 'Thriller' }],
    popularity: 180.2,
    originalLanguage: 'en',
    runtime: 121,
    tagline: 'Vengeance becomes him.',
    status: 'Released',
    cast: [
      { id: 52783, name: 'Dev Patel', character: 'Kid', profileUrl: null },
      { id: 52784, name: 'Sharlto Copley', character: 'Tiger', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  }
];

export const fallbackPopular: MovieDetails[] = [
  {
    id: 569094,
    title: 'Spider-Man: Across the Spider-Verse',
    originalTitle: 'Spider-Man: Across the Spider-Verse',
    overview: 'After reuniting with Gwen Stacy, Brooklyn\'s full-time Spider-Man is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    rating: 8.4,
    voteCount: 7100,
    releaseDate: '2023-05-31',
    releaseYear: 2023,
    genreIds: [16, 28, 12, 878],
    genres: ['Animation', 'Action', 'Adventure', 'Science Fiction'],
    genreObjects: [{ id: 16, name: 'Animation' }, { id: 28, name: 'Action' }],
    popularity: 290.0,
    originalLanguage: 'en',
    runtime: 140,
    tagline: 'It\'s how you wear the mask that matters.',
    status: 'Released',
    cast: [
      { id: 587506, name: 'Shameik Moore', character: 'Miles Morales (voice)', profileUrl: null },
      { id: 54693, name: 'Hailee Steinfeld', character: 'Gwen Stacy (voice)', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 346698,
    title: 'Barbie',
    originalTitle: 'Barbie',
    overview: 'To live in Barbie Land is to be a perfect being in a perfect place. Unless you have a full-on existential crisis. Or you\'re a Ken.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
    rating: 7.1,
    voteCount: 8900,
    releaseDate: '2023-07-19',
    releaseYear: 2023,
    genreIds: [35, 12],
    genres: ['Comedy', 'Adventure'],
    genreObjects: [{ id: 35, name: 'Comedy' }, { id: 12, name: 'Adventure' }],
    popularity: 310.2,
    originalLanguage: 'en',
    runtime: 114,
    tagline: 'She can do everything. He\'s just Ken.',
    status: 'Released',
    cast: [
      { id: 234352, name: 'Margot Robbie', character: 'Barbie', profileUrl: null },
      { id: 30614, name: 'Ryan Gosling', character: 'Ken', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 361743,
    title: 'Top Gun: Maverick',
    originalTitle: 'Top Gun: Maverick',
    overview: 'After thirty years of service as a top naval aviator, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/AaV1YIdWKnjAiaOe0UUKNJm922w.jpg',
    rating: 8.2,
    voteCount: 9200,
    releaseDate: '2022-05-24',
    releaseYear: 2022,
    genreIds: [28, 18],
    genres: ['Action', 'Drama'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 18, name: 'Drama' }],
    popularity: 275.5,
    originalLanguage: 'en',
    runtime: 130,
    tagline: 'Feel the need... The need for speed.',
    status: 'Released',
    cast: [
      { id: 500, name: 'Tom Cruise', character: 'Capt. Pete \'Maverick\' Mitchell', profileUrl: null },
      { id: 1253364, name: 'Miles Teller', character: 'Lt. Bradley \'Rooster\' Bradshaw', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 414906,
    title: 'The Batman',
    originalTitle: 'The Batman',
    overview: 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
    rating: 7.7,
    voteCount: 9800,
    releaseDate: '2022-03-01',
    releaseYear: 2022,
    genreIds: [80, 9648, 28],
    genres: ['Crime', 'Mystery', 'Action'],
    genreObjects: [{ id: 80, name: 'Crime' }, { id: 28, name: 'Action' }],
    popularity: 260.8,
    originalLanguage: 'en',
    runtime: 176,
    tagline: 'Unmask the truth.',
    status: 'Released',
    cast: [
      { id: 11288, name: 'Robert Pattinson', character: 'Bruce Wayne / The Batman', profileUrl: null },
      { id: 37153, name: 'Zoë Kravitz', character: 'Selina Kyle / Catwoman', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 76600,
    title: 'Avatar: The Way of Water',
    originalTitle: 'Avatar: The Way of Water',
    overview: 'Set more than a decade after the events of the first film, learn the story of the Sully family, the trouble that follows them, and the lengths they go to keep each other safe.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg',
    rating: 7.6,
    voteCount: 11400,
    releaseDate: '2022-12-14',
    releaseYear: 2022,
    genreIds: [878, 12, 28],
    genres: ['Science Fiction', 'Adventure', 'Action'],
    genreObjects: [{ id: 878, name: 'Science Fiction' }, { id: 12, name: 'Adventure' }],
    popularity: 285.0,
    originalLanguage: 'en',
    runtime: 192,
    tagline: 'Return to Pandora.',
    status: 'Released',
    cast: [
      { id: 65731, name: 'Sam Worthington', character: 'Jake Sully', profileUrl: null },
      { id: 8691, name: 'Zoe Saldaña', character: 'Neytiri', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 545611,
    title: 'Everything Everywhere All at Once',
    originalTitle: 'Everything Everywhere All at Once',
    overview: 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what is important to her by connecting with other lives she could have led in parallel universes.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/u68AjlvlutfEIcpmbYpKcdi09ut.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/ss0Os3uW2Q7U2z68w2H8p8i5T.jpg',
    rating: 7.8,
    voteCount: 6200,
    releaseDate: '2022-03-24',
    releaseYear: 2022,
    genreIds: [28, 12, 878, 35],
    genres: ['Action', 'Adventure', 'Science Fiction', 'Comedy'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 878, name: 'Science Fiction' }],
    popularity: 245.4,
    originalLanguage: 'en',
    runtime: 139,
    tagline: 'The universe is so much bigger than your problems.',
    status: 'Released',
    cast: [
      { id: 1620, name: 'Michelle Yeoh', character: 'Evelyn Wang', profileUrl: null },
      { id: 23659, name: 'Ke Huy Quan', character: 'Waymond Wang', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 603692,
    title: 'John Wick: Chapter 4',
    originalTitle: 'John Wick: Chapter 4',
    overview: 'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table, but before he can earn his freedom, he must face off against a new enemy.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/sP7MVWz9Fi5nkLmRCNKXnlcKkdb.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/7I6VUdPj6tQECNHdviJkUHD2389.jpg',
    rating: 7.7,
    voteCount: 6500,
    releaseDate: '2023-03-22',
    releaseYear: 2023,
    genreIds: [28, 53, 80],
    genres: ['Action', 'Thriller', 'Crime'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 53, name: 'Thriller' }],
    popularity: 255.0,
    originalLanguage: 'en',
    runtime: 169,
    tagline: 'No way back. One way out.',
    status: 'Released',
    cast: [
      { id: 6384, name: 'Keanu Reeves', character: 'John Wick', profileUrl: null },
      { id: 1333, name: 'Donnie Yen', character: 'Caine', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 447365,
    title: 'Guardians of the Galaxy Vol. 3',
    originalTitle: 'Guardians of the Galaxy Vol. 3',
    overview: 'Peter Quill, still reeling from the loss of Gamora, rallies his team to defend the universe and one of their own on a mission that could mean the end of the Guardians.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN2Ydgii51I3.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
    rating: 7.9,
    voteCount: 6800,
    releaseDate: '2023-05-03',
    releaseYear: 2023,
    genreIds: [878, 12, 28],
    genres: ['Science Fiction', 'Adventure', 'Action'],
    genreObjects: [{ id: 878, name: 'Science Fiction' }, { id: 28, name: 'Action' }],
    popularity: 265.2,
    originalLanguage: 'en',
    runtime: 150,
    tagline: 'Once more with feeling.',
    status: 'Released',
    cast: [
      { id: 73457, name: 'Chris Pratt', character: 'Peter Quill / Star-Lord', profileUrl: null },
      { id: 8691, name: 'Zoe Saldaña', character: 'Gamora', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 157336,
    title: 'Interstellar',
    originalTitle: 'Interstellar',
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival beyond a dying Earth.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    rating: 8.4,
    voteCount: 35400,
    releaseDate: '2014-11-05',
    releaseYear: 2014,
    genreIds: [12, 18, 878],
    genres: ['Adventure', 'Drama', 'Science Fiction'],
    genreObjects: [{ id: 12, name: 'Adventure' }, { id: 878, name: 'Science Fiction' }],
    popularity: 290.4,
    originalLanguage: 'en',
    runtime: 169,
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    status: 'Released',
    cast: [
      { id: 10297, name: 'Matthew McConaughey', character: 'Joseph Cooper', profileUrl: 'https://image.tmdb.org/t/p/w185/eD1d03M2j46a9qGg4u848P2bF7E.jpg' },
      { id: 1813, name: 'Anne Hathaway', character: 'Dr. Amelia Brand', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 27205,
    title: 'Inception',
    originalTitle: 'Inception',
    overview: 'Cobb, a skilled thief who steals corporate secrets through dream-sharing technology, is given the inverse task of planting an idea into the mind of a C.E.O.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    rating: 8.4,
    voteCount: 36200,
    releaseDate: '2010-07-15',
    releaseYear: 2010,
    genreIds: [28, 878, 12],
    genres: ['Action', 'Science Fiction', 'Adventure'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 878, name: 'Science Fiction' }],
    popularity: 260.8,
    originalLanguage: 'en',
    runtime: 148,
    tagline: 'Your mind is the scene of the crime.',
    status: 'Released',
    cast: [
      { id: 6193, name: 'Leonardo DiCaprio', character: 'Dom Cobb', profileUrl: 'https://image.tmdb.org/t/p/w185/wo250aPwfXfF26L7Gq7z2Q09c4v.jpg' },
      { id: 24045, name: 'Joseph Gordon-Levitt', character: 'Arthur', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 502356,
    title: 'The Super Mario Bros. Movie',
    originalTitle: 'The Super Mario Bros. Movie',
    overview: 'While working underground to fix a water main, Brooklyn plumbers Mario and brother Luigi are transported down a mysterious pipe into a magical new world.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/9n2tJBplPbgR2ca05hR5U7wmuCV.jpg',
    rating: 7.7,
    voteCount: 8800,
    releaseDate: '2023-04-05',
    releaseYear: 2023,
    genreIds: [16, 10751, 12, 14],
    genres: ['Animation', 'Family', 'Adventure', 'Fantasy'],
    genreObjects: [{ id: 16, name: 'Animation' }, { id: 10751, name: 'Family' }],
    popularity: 270.0,
    originalLanguage: 'en',
    runtime: 92,
    tagline: 'Let\'s-a go!',
    status: 'Released',
    cast: [
      { id: 73457, name: 'Chris Pratt', character: 'Mario (voice)', profileUrl: null },
      { id: 139, name: 'Anya Taylor-Joy', character: 'Princess Peach (voice)', profileUrl: null },
      { id: 70851, name: 'Jack Black', character: 'Bowser (voice)', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 575264,
    title: 'Mission: Impossible - Dead Reckoning Part One',
    originalTitle: 'Mission: Impossible - Dead Reckoning Part One',
    overview: 'Ethan Hunt and his IMF team embark on their most dangerous mission yet: to track down a terrifying new weapon that threatens all of humanity.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/628Dep6AxEtDxjZoGP78TsOxYbK.jpg',
    rating: 7.6,
    voteCount: 3900,
    releaseDate: '2023-07-08',
    releaseYear: 2023,
    genreIds: [28, 53],
    genres: ['Action', 'Thriller'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 53, name: 'Thriller' }],
    popularity: 250.0,
    originalLanguage: 'en',
    runtime: 163,
    tagline: 'We all share the same fate.',
    status: 'Released',
    cast: [
      { id: 500, name: 'Tom Cruise', character: 'Ethan Hunt', profileUrl: null },
      { id: 5293, name: 'Hayley Atwell', character: 'Grace', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  }
];

export const fallbackTopRated: MovieDetails[] = [
  {
    id: 278,
    title: 'The Shawshank Redemption',
    originalTitle: 'The Shawshank Redemption',
    overview: 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, forging a lasting bond with fellow inmate Red.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    rating: 8.7,
    voteCount: 26400,
    releaseDate: '1994-09-23',
    releaseYear: 1994,
    genreIds: [18, 80],
    genres: ['Drama', 'Crime'],
    genreObjects: [{ id: 18, name: 'Drama' }, { id: 80, name: 'Crime' }],
    popularity: 160.4,
    originalLanguage: 'en',
    runtime: 142,
    tagline: 'Fear can hold you prisoner. Hope can set you free.',
    status: 'Released',
    cast: [
      { id: 504, name: 'Tim Robbins', character: 'Andy Dufresne', profileUrl: null },
      { id: 192, name: 'Morgan Freeman', character: 'Ellis Boyd \'Red\' Redding', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 238,
    title: 'The Godfather',
    originalTitle: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When patriarch Vito Corleone barely survives an assassination attempt, his youngest son steps up.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    rating: 8.7,
    voteCount: 19900,
    releaseDate: '1972-03-14',
    releaseYear: 1972,
    genreIds: [18, 80],
    genres: ['Drama', 'Crime'],
    genreObjects: [{ id: 18, name: 'Drama' }, { id: 80, name: 'Crime' }],
    popularity: 155.2,
    originalLanguage: 'en',
    runtime: 175,
    tagline: 'An offer you can\'t refuse.',
    status: 'Released',
    cast: [
      { id: 3084, name: 'Marlon Brando', character: 'Don Vito Corleone', profileUrl: null },
      { id: 1158, name: 'Al Pacino', character: 'Michael Corleone', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 155,
    title: 'The Dark Knight',
    originalTitle: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and DA Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    rating: 8.5,
    voteCount: 32500,
    releaseDate: '2008-07-16',
    releaseYear: 2008,
    genreIds: [18, 28, 80, 53],
    genres: ['Drama', 'Action', 'Crime', 'Thriller'],
    genreObjects: [{ id: 18, name: 'Drama' }, { id: 28, name: 'Action' }],
    popularity: 240.2,
    originalLanguage: 'en',
    runtime: 152,
    tagline: 'Why so serious?',
    status: 'Released',
    cast: [
      { id: 3894, name: 'Christian Bale', character: 'Bruce Wayne / Batman', profileUrl: null },
      { id: 1810, name: 'Heath Ledger', character: 'Joker', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 389,
    title: '12 Angry Men',
    originalTitle: '12 Angry Men',
    overview: 'The defense and the prosecution have rested and the jury is filing into the jury room to decide if an eighteen-year-old boy is guilty of murdering his father.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/qqHQsStV6exghCM7zbR6eI6e054.jpg',
    rating: 8.5,
    voteCount: 8300,
    releaseDate: '1957-04-10',
    releaseYear: 1957,
    genreIds: [18],
    genres: ['Drama'],
    genreObjects: [{ id: 18, name: 'Drama' }],
    popularity: 110.5,
    originalLanguage: 'en',
    runtime: 96,
    tagline: 'Life is in their hands. Death is on their minds.',
    status: 'Released',
    cast: [
      { id: 4958, name: 'Henry Fonda', character: 'Juror 8', profileUrl: null },
      { id: 4959, name: 'Lee J. Cobb', character: 'Juror 3', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 424,
    title: 'Schindler\'s List',
    originalTitle: 'Schindler\'s List',
    overview: 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while exploiting them as workers in his factory.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/zb6fM1CX41D9rF9hdgAv0g2Smt5.jpg',
    rating: 8.6,
    voteCount: 15500,
    releaseDate: '1993-12-15',
    releaseYear: 1993,
    genreIds: [18, 36, 10752],
    genres: ['Drama', 'History', 'War'],
    genreObjects: [{ id: 18, name: 'Drama' }, { id: 36, name: 'History' }],
    popularity: 130.0,
    originalLanguage: 'en',
    runtime: 195,
    tagline: 'Whoever saves one life, saves the world entire.',
    status: 'Released',
    cast: [
      { id: 3895, name: 'Liam Neeson', character: 'Oskar Schindler', profileUrl: null },
      { id: 2282, name: 'Ben Kingsley', character: 'Itzhak Stern', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 680,
    title: 'Pulp Fiction',
    originalTitle: 'Pulp Fiction',
    overview: 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling comedic crime caper.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    rating: 8.5,
    voteCount: 27200,
    releaseDate: '1994-09-10',
    releaseYear: 1994,
    genreIds: [53, 80],
    genres: ['Thriller', 'Crime'],
    genreObjects: [{ id: 53, name: 'Thriller' }, { id: 80, name: 'Crime' }],
    popularity: 170.8,
    originalLanguage: 'en',
    runtime: 154,
    tagline: 'Just because you are a character doesn\'t mean you have character.',
    status: 'Released',
    cast: [
      { id: 8891, name: 'John Travolta', character: 'Vincent Vega', profileUrl: null },
      { id: 2231, name: 'Samuel L. Jackson', character: 'Jules Winnfield', profileUrl: null },
      { id: 139, name: 'Uma Thurman', character: 'Mia Wallace', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 122,
    title: 'The Lord of the Rings: The Return of the King',
    originalTitle: 'The Lord of the Rings: The Return of the King',
    overview: 'Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron\'s forces.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
    rating: 8.6,
    voteCount: 23600,
    releaseDate: '2003-12-01',
    releaseYear: 2003,
    genreIds: [12, 14, 28],
    genres: ['Adventure', 'Fantasy', 'Action'],
    genreObjects: [{ id: 12, name: 'Adventure' }, { id: 14, name: 'Fantasy' }],
    popularity: 190.4,
    originalLanguage: 'en',
    runtime: 201,
    tagline: 'The eye of the enemy is moving.',
    status: 'Released',
    cast: [
      { id: 109, name: 'Elijah Wood', character: 'Frodo Baggins', profileUrl: null },
      { id: 110, name: 'Ian McKellen', character: 'Gandalf', profileUrl: null },
      { id: 111, name: 'Viggo Mortensen', character: 'Aragorn', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 129,
    title: 'Spirited Away',
    originalTitle: '千と千尋の神隠し',
    overview: 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg',
    rating: 8.5,
    voteCount: 16300,
    releaseDate: '2001-07-20',
    releaseYear: 2001,
    genreIds: [16, 10751, 14],
    genres: ['Animation', 'Family', 'Fantasy'],
    genreObjects: [{ id: 16, name: 'Animation' }, { id: 10751, name: 'Family' }],
    popularity: 175.2,
    originalLanguage: 'ja',
    runtime: 125,
    tagline: 'The tunnel led Chihiro to a mysterious world...',
    status: 'Released',
    cast: [
      { id: 19588, name: 'Rumi Hiiragi', character: 'Chihiro Ogino (voice)', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 496243,
    title: 'Parasite',
    originalTitle: '기생충',
    overview: 'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
    rating: 8.5,
    voteCount: 17800,
    releaseDate: '2019-05-30',
    releaseYear: 2019,
    genreIds: [35, 53, 18],
    genres: ['Comedy', 'Thriller', 'Drama'],
    genreObjects: [{ id: 35, name: 'Comedy' }, { id: 53, name: 'Thriller' }],
    popularity: 195.4,
    originalLanguage: 'ko',
    runtime: 133,
    tagline: 'Act like you own the place.',
    status: 'Released',
    cast: [
      { id: 20738, name: 'Song Kang-ho', character: 'Kim Ki-taek', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 769,
    title: 'GoodFellas',
    originalTitle: 'GoodFellas',
    overview: 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/sw7mordbZxgITU877yTpZCud90M.jpg',
    rating: 8.5,
    voteCount: 12500,
    releaseDate: '1990-09-12',
    releaseYear: 1990,
    genreIds: [18, 80],
    genres: ['Drama', 'Crime'],
    genreObjects: [{ id: 18, name: 'Drama' }, { id: 80, name: 'Crime' }],
    popularity: 145.6,
    originalLanguage: 'en',
    runtime: 145,
    tagline: 'Three Decades of Life in the Mafia.',
    status: 'Released',
    cast: [
      { id: 1032, name: 'Ray Liotta', character: 'Henry Hill', profileUrl: null },
      { id: 1038, name: 'Robert De Niro', character: 'James Conway', profileUrl: null },
      { id: 4566, name: 'Joe Pesci', character: 'Tommy DeVito', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 550,
    title: 'Fight Club',
    originalTitle: 'Fight Club',
    overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    rating: 8.4,
    voteCount: 28700,
    releaseDate: '1999-10-15',
    releaseYear: 1999,
    genreIds: [18],
    genres: ['Drama'],
    genreObjects: [{ id: 18, name: 'Drama' }],
    popularity: 165.2,
    originalLanguage: 'en',
    runtime: 139,
    tagline: 'Mischief. Mayhem. Soap.',
    status: 'Released',
    cast: [
      { id: 819, name: 'Edward Norton', character: 'The Narrator', profileUrl: null },
      { id: 287, name: 'Brad Pitt', character: 'Tyler Durden', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 13,
    title: 'Forrest Gump',
    originalTitle: 'Forrest Gump',
    overview: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
    rating: 8.5,
    voteCount: 26800,
    releaseDate: '1994-06-23',
    releaseYear: 1994,
    genreIds: [35, 18, 10749],
    genres: ['Comedy', 'Drama', 'Romance'],
    genreObjects: [{ id: 35, name: 'Comedy' }, { id: 18, name: 'Drama' }],
    popularity: 168.0,
    originalLanguage: 'en',
    runtime: 142,
    tagline: 'Life is like a box of chocolates... you never know what you\'re gonna get.',
    status: 'Released',
    cast: [
      { id: 31, name: 'Tom Hanks', character: 'Forrest Gump', profileUrl: null },
      { id: 32, name: 'Robin Wright', character: 'Jenny Curran', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  }
];

export const fallbackNowPlaying: MovieDetails[] = [
  {
    id: 1022789,
    title: 'Inside Out 2',
    originalTitle: 'Inside Out 2',
    overview: 'Teenager Riley\'s mind headquarters is undergoing a sudden demolition to make room for unexpected new Emotions: Anxiety, Envy, Ennui, and Embarrassment.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/stKGOmXZpg1iKyF8u19vUsc9fio.jpg',
    rating: 7.6,
    voteCount: 4200,
    ...getRelativeDate(-14),
    genreIds: [16, 10751, 35],
    genres: ['Animation', 'Family', 'Comedy'],
    genreObjects: [{ id: 16, name: 'Animation' }, { id: 10751, name: 'Family' }],
    popularity: 350.2,
    originalLanguage: 'en',
    runtime: 96,
    tagline: 'Make room for new emotions.',
    status: 'Released',
    cast: [
      { id: 1253365, name: 'Amy Poehler', character: 'Joy (voice)', profileUrl: null },
      { id: 1253366, name: 'Maya Hawke', character: 'Anxiety (voice)', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 533535,
    title: 'Deadpool & Wolverine',
    originalTitle: 'Deadpool & Wolverine',
    overview: 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary behind him. But when his homeworld faces an existential threat, he must recruit a reluctant Wolverine.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
    rating: 7.7,
    voteCount: 4900,
    ...getRelativeDate(-21),
    genreIds: [28, 35, 878],
    genres: ['Action', 'Comedy', 'Science Fiction'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 35, name: 'Comedy' }],
    popularity: 390.4,
    originalLanguage: 'en',
    runtime: 128,
    tagline: 'Everyone deserves a happy ending.',
    status: 'Released',
    cast: [
      { id: 10859, name: 'Ryan Reynolds', character: 'Wade Wilson / Deadpool', profileUrl: null },
      { id: 6968, name: 'Hugh Jackman', character: 'Logan / Wolverine', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 653346,
    title: 'Kingdom of the Planet of the Apes',
    originalTitle: 'Kingdom of the Planet of the Apes',
    overview: 'Several generations following Caesar\'s reign, apes are now the dominant species living harmoniously, while humans have been reduced to living in the shadows.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/fqv8v6AycXKsivp1TFXoKtqRp3Z.jpg',
    rating: 7.1,
    voteCount: 2900,
    ...getRelativeDate(-35),
    genreIds: [878, 12, 28],
    genres: ['Science Fiction', 'Adventure', 'Action'],
    genreObjects: [{ id: 878, name: 'Science Fiction' }, { id: 28, name: 'Action' }],
    popularity: 280.0,
    originalLanguage: 'en',
    runtime: 145,
    tagline: 'No one can stop the reign.',
    status: 'Released',
    cast: [
      { id: 1253367, name: 'Owen Teague', character: 'Noa (voice)', profileUrl: null },
      { id: 1253368, name: 'Freya Allan', character: 'Nova / Mae', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 718821,
    title: 'Twisters',
    originalTitle: 'Twisters',
    overview: 'As storm season intensifies, the paths of former storm chaser Kate Cooper and reckless social-media superstar Tyler Owens collide in Oklahoma.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/581clnuh0UNxQ6900tZq.jpg',
    rating: 7.0,
    voteCount: 1800,
    ...getRelativeDate(-28),
    genreIds: [28, 12, 18],
    genres: ['Action', 'Adventure', 'Drama'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 12, name: 'Adventure' }],
    popularity: 250.6,
    originalLanguage: 'en',
    runtime: 122,
    tagline: 'Chase the storm.',
    status: 'Released',
    cast: [
      { id: 1253369, name: 'Daisy Edgar-Jones', character: 'Kate Carter', profileUrl: null },
      { id: 1253370, name: 'Glen Powell', character: 'Tyler Owens', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 762441,
    title: 'A Quiet Place: Day One',
    originalTitle: 'A Quiet Place: Day One',
    overview: 'Experience the day the world went quiet as mysterious sound-hunting creatures invade New York City in this terrifying prequel.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/hU42CRk14JuPEdqZG3AWmagiPAP.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/2RVcJbWFmICRDUNqIO8cqBpQAin.jpg',
    rating: 6.9,
    voteCount: 2100,
    ...getRelativeDate(-42),
    genreIds: [27, 878, 53],
    genres: ['Horror', 'Science Fiction', 'Thriller'],
    genreObjects: [{ id: 27, name: 'Horror' }, { id: 878, name: 'Science Fiction' }],
    popularity: 240.2,
    originalLanguage: 'en',
    runtime: 99,
    tagline: 'Hear how it all began.',
    status: 'Released',
    cast: [
      { id: 1253371, name: 'Lupita Nyong\'o', character: 'Samira', profileUrl: null },
      { id: 1253372, name: 'Joseph Quinn', character: 'Eric', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 945961,
    title: 'Alien: Romulus',
    originalTitle: 'Alien: Romulus',
    overview: 'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/9SSEUrSqhljBMzRe4aBTE1nxKoH.jpg',
    rating: 7.3,
    voteCount: 2300,
    ...getRelativeDate(-7),
    genreIds: [27, 878],
    genres: ['Horror', 'Science Fiction'],
    genreObjects: [{ id: 27, name: 'Horror' }, { id: 878, name: 'Science Fiction' }],
    popularity: 290.4,
    originalLanguage: 'en',
    runtime: 119,
    tagline: 'In space no one can hear you scream.',
    status: 'Released',
    cast: [
      { id: 1253373, name: 'Cailee Spaeny', character: 'Rain Carradine', profileUrl: null },
      { id: 1253374, name: 'David Jonsson', character: 'Andy', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 573435,
    title: 'Bad Boys: Ride or Die',
    originalTitle: 'Bad Boys: Ride or Die',
    overview: 'Miami\'s favorite Bad Boys are back with their iconic mix of edge-of-your-seat action and outrageous comedy, but this time they\'re on the run.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oGythE98MYleE6mZlGs5oBGkux1.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/ga4OLm4qLxO1YMiohk3vP8kG.jpg',
    rating: 7.5,
    voteCount: 2400,
    ...getRelativeDate(-30),
    genreIds: [28, 35, 80],
    genres: ['Action', 'Comedy', 'Crime'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 35, name: 'Comedy' }],
    popularity: 235.0,
    originalLanguage: 'en',
    runtime: 115,
    tagline: 'Miami\'s finest are now Miami\'s most wanted.',
    status: 'Released',
    cast: [
      { id: 2888, name: 'Will Smith', character: 'Detective Mike Lowrey', profileUrl: null },
      { id: 78798, name: 'Martin Lawrence', character: 'Detective Marcus Burnett', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 519182,
    title: 'Despicable Me 4',
    originalTitle: 'Despicable Me 4',
    overview: 'Gru and Lucy and their girls welcome a new member to the family, Gru Jr., who is intent on tormenting his dad as a new nemesis emerges.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/wWba3TaojhK7NdycRhoQpsG0FaH.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/lgkFtNmd2vCokmVe3fvg2Zr7J.jpg',
    rating: 7.1,
    voteCount: 2100,
    ...getRelativeDate(-25),
    genreIds: [16, 10751, 35],
    genres: ['Animation', 'Family', 'Comedy'],
    genreObjects: [{ id: 16, name: 'Animation' }, { id: 10751, name: 'Family' }],
    popularity: 260.0,
    originalLanguage: 'en',
    runtime: 95,
    tagline: 'Things just got a little more despicable.',
    status: 'Released',
    cast: [
      { id: 23659, name: 'Steve Carell', character: 'Gru (voice)', profileUrl: null },
      { id: 3290, name: 'Kristen Wiig', character: 'Lucy Wilde (voice)', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 1226578,
    title: 'Longlegs',
    originalTitle: 'Longlegs',
    overview: 'FBI Agent Lee Harker is assigned to an unsolved serial killer case that takes an unexpected turn, revealing evidence of the occult.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1EwNyiiNFd863H4e8nWEzutnZD7.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/fzmYzmrQNZ3IkfnkXGgomNzJ5eR.jpg',
    rating: 6.7,
    voteCount: 1200,
    ...getRelativeDate(-18),
    genreIds: [80, 27, 53],
    genres: ['Crime', 'Horror', 'Thriller'],
    genreObjects: [{ id: 80, name: 'Crime' }, { id: 27, name: 'Horror' }],
    popularity: 210.0,
    originalLanguage: 'en',
    runtime: 101,
    tagline: 'Say your prayers.',
    status: 'Released',
    cast: [
      { id: 1253375, name: 'Maika Monroe', character: 'Lee Harker', profileUrl: null },
      { id: 2963, name: 'Nicolas Cage', character: 'The Man Downstairs', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 956842,
    title: 'Fly Me to the Moon',
    originalTitle: 'Fly Me to the Moon',
    overview: 'Sparks fly between a marketing maven brought in to fix NASA\'s public image and the launch director in charge of the historic Apollo 11 moon landing.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/fzmYzmrQNZ3IkfnkXGgomNzJ5eR.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/jwoaKYVqPgYemFpaANL941EF94R.jpg',
    rating: 6.9,
    voteCount: 850,
    ...getRelativeDate(-12),
    genreIds: [35, 10749],
    genres: ['Comedy', 'Romance'],
    genreObjects: [{ id: 35, name: 'Comedy' }, { id: 10749, name: 'Romance' }],
    popularity: 170.0,
    originalLanguage: 'en',
    runtime: 132,
    tagline: 'The whole world is watching.',
    status: 'Released',
    cast: [
      { id: 1245, name: 'Scarlett Johansson', character: 'Kelly Jones', profileUrl: null },
      { id: 3223, name: 'Channing Tatum', character: 'Cole Davis', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 1032823,
    title: 'Trap',
    originalTitle: 'Trap',
    overview: 'A father and teen daughter attend a pop concert, where they realize they\'re at the center of a dark and sinister police manhunt.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/jwoaKYVqPgYemFpaANL941EF94R.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg',
    rating: 6.5,
    voteCount: 1500,
    ...getRelativeDate(-5),
    genreIds: [53, 80],
    genres: ['Thriller', 'Crime'],
    genreObjects: [{ id: 53, name: 'Thriller' }, { id: 80, name: 'Crime' }],
    popularity: 200.0,
    originalLanguage: 'en',
    runtime: 105,
    tagline: '30,000 fans. 300 cops. 1 serial killer.',
    status: 'Released',
    cast: [
      { id: 1253376, name: 'Josh Hartnett', character: 'Cooper Adams', profileUrl: null },
      { id: 1253377, name: 'Ariel Donoghue', character: 'Riley Adams', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 1079091,
    title: 'It Ends with Us',
    originalTitle: 'It Ends with Us',
    overview: 'Lily Bloom moves to Boston to chase her dream of opening a flower shop. A chance meeting with charming neurosurgeon Ryle Kincaid sparks an intense connection.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/6Pqu2fenaC1izVGmoSSBwF9iYuL.jpg',
    rating: 7.2,
    voteCount: 1100,
    ...getRelativeDate(-10),
    genreIds: [18, 10749],
    genres: ['Drama', 'Romance'],
    genreObjects: [{ id: 18, name: 'Drama' }, { id: 10749, name: 'Romance' }],
    popularity: 215.0,
    originalLanguage: 'en',
    runtime: 130,
    tagline: 'We break the pattern, or the pattern breaks us.',
    status: 'Released',
    cast: [
      { id: 1253378, name: 'Blake Lively', character: 'Lily Bloom', profileUrl: null },
      { id: 1253379, name: 'Justin Baldoni', character: 'Ryle Kincaid', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  }
];

export const fallbackUpcoming: MovieDetails[] = [
  {
    id: 558449,
    title: 'Gladiator II',
    originalTitle: 'Gladiator II',
    overview: 'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/euYIwmwkmz95mnExVOvRw541QeG.jpg',
    rating: 7.4,
    voteCount: 1800,
    ...getRelativeDate(30),
    genreIds: [28, 12, 18],
    genres: ['Action', 'Adventure', 'Drama'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 12, name: 'Adventure' }],
    popularity: 340.5,
    originalLanguage: 'en',
    runtime: 148,
    tagline: 'What we do in life echoes in eternity.',
    status: 'Post Production',
    cast: [
      { id: 1253380, name: 'Paul Mescal', character: 'Lucius Verus', profileUrl: null },
      { id: 1253381, name: 'Pedro Pascal', character: 'Marcus Acacius', profileUrl: null },
      { id: 192, name: 'Denzel Washington', character: 'Macrinus', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 889737,
    title: 'Joker: Folie à Deux',
    originalTitle: 'Joker: Folie à Deux',
    overview: 'While incarcerated at Arkham State Hospital, Arthur Fleck falls in love with music therapist Harleen Quinzel as a musical madness begins to unfold.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/6Pqu2fenaC1izVGmoSSBwF9iYuL.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg',
    rating: 6.8,
    voteCount: 1600,
    ...getRelativeDate(45),
    genreIds: [18, 80, 53],
    genres: ['Drama', 'Crime', 'Thriller'],
    genreObjects: [{ id: 18, name: 'Drama' }, { id: 80, name: 'Crime' }],
    popularity: 310.0,
    originalLanguage: 'en',
    runtime: 138,
    tagline: 'The world is a stage.',
    status: 'Post Production',
    cast: [
      { id: 7342, name: 'Joaquin Phoenix', character: 'Arthur Fleck / Joker', profileUrl: null },
      { id: 1253382, name: 'Lady Gaga', character: 'Harleen \'Lee\' Quinzel', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 402431,
    title: 'Wicked',
    originalTitle: 'Wicked',
    overview: 'Elphaba, a misunderstood young woman with green skin, and Glinda, a popular blonde, meet as students at Shiz University in the Land of Oz and forge an unlikely friendship.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg',
    rating: 7.5,
    voteCount: 1200,
    ...getRelativeDate(60),
    genreIds: [14, 10749, 18],
    genres: ['Fantasy', 'Romance', 'Drama'],
    genreObjects: [{ id: 14, name: 'Fantasy' }, { id: 18, name: 'Drama' }],
    popularity: 280.2,
    originalLanguage: 'en',
    runtime: 160,
    tagline: 'Defy gravity.',
    status: 'Post Production',
    cast: [
      { id: 1253383, name: 'Cynthia Erivo', character: 'Elphaba Thropp', profileUrl: null },
      { id: 1253384, name: 'Ariana Grande', character: 'Glinda Upland', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 426063,
    title: 'Nosferatu',
    originalTitle: 'Nosferatu',
    overview: 'A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg',
    rating: 7.2,
    voteCount: 900,
    ...getRelativeDate(90),
    genreIds: [27, 14],
    genres: ['Horror', 'Fantasy'],
    genreObjects: [{ id: 27, name: 'Horror' }, { id: 14, name: 'Fantasy' }],
    popularity: 270.0,
    originalLanguage: 'en',
    runtime: 132,
    tagline: 'He is coming.',
    status: 'Post Production',
    cast: [
      { id: 1253385, name: 'Bill Skarsgård', character: 'Count Orlok', profileUrl: null },
      { id: 1253386, name: 'Lily-Rose Depp', character: 'Ellen Hutter', profileUrl: null },
      { id: 1253387, name: 'Nicholas Hoult', character: 'Thomas Hutter', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 762509,
    title: 'Mufasa: The Lion King',
    originalTitle: 'Mufasa: The Lion King',
    overview: 'Told in flashbacks, Rafiki recounts the rise of one of the Pride Lands\' greatest kings, Mufasa, to his curious granddaughter Kiara.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg',
    rating: 7.1,
    voteCount: 800,
    ...getRelativeDate(100),
    genreIds: [12, 10751, 16],
    genres: ['Adventure', 'Family', 'Animation'],
    genreObjects: [{ id: 12, name: 'Adventure' }, { id: 10751, name: 'Family' }],
    popularity: 255.0,
    originalLanguage: 'en',
    runtime: 118,
    tagline: 'An orphan became a king.',
    status: 'Post Production',
    cast: [
      { id: 1253388, name: 'Aaron Pierre', character: 'Mufasa (voice)', profileUrl: null },
      { id: 1253389, name: 'Kelvin Harrison Jr.', character: 'Taka (voice)', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 822119,
    title: 'Captain America: Brave New World',
    originalTitle: 'Captain America: Brave New World',
    overview: 'After meeting with newly elected U.S. President Thaddeus Ross, Sam Wilson finds himself in the middle of an international incident.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/1GvBhRxY6MELDfxFrete6BNhBB5.jpg',
    rating: 7.0,
    voteCount: 500,
    ...getRelativeDate(140),
    genreIds: [28, 878, 53],
    genres: ['Action', 'Science Fiction', 'Thriller'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 878, name: 'Science Fiction' }],
    popularity: 260.0,
    originalLanguage: 'en',
    runtime: 125,
    tagline: 'A new world order.',
    status: 'Post Production',
    cast: [
      { id: 53659, name: 'Anthony Mackie', character: 'Sam Wilson / Captain America', profileUrl: null },
      { id: 3, name: 'Harrison Ford', character: 'Thaddeus \'Thunderbolt\' Ross', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 1241982,
    title: 'Moana 2',
    originalTitle: 'Moana 2',
    overview: 'After receiving an unexpected call from her wayfinding ancestors, Moana must journey to the far seas of Oceania and into dangerous waters for an adventure unlike any she has faced.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg',
    rating: 7.3,
    voteCount: 1100,
    ...getRelativeDate(75),
    genreIds: [16, 10751, 12],
    genres: ['Animation', 'Family', 'Adventure'],
    genreObjects: [{ id: 16, name: 'Animation' }, { id: 10751, name: 'Family' }],
    popularity: 275.4,
    originalLanguage: 'en',
    runtime: 100,
    tagline: 'The ocean is calling her back.',
    status: 'Post Production',
    cast: [
      { id: 1253390, name: 'Auli\'i Cravalho', character: 'Moana (voice)', profileUrl: null },
      { id: 18918, name: 'Dwayne Johnson', character: 'Maui (voice)', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 539972,
    title: 'Kraven the Hunter',
    originalTitle: 'Kraven the Hunter',
    overview: 'Kraven\'s complex relationship with his ruthless father Nikolai Kravinoff starts him on a path of vengeance with brutal consequences.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1GvBhRxY6MELDfxFrete6BNhBB5.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/cgXk2tNYhJZLXdBDO5DidAVzQ82.jpg',
    rating: 6.8,
    voteCount: 600,
    ...getRelativeDate(85),
    genreIds: [28, 12, 53],
    genres: ['Action', 'Adventure', 'Thriller'],
    genreObjects: [{ id: 28, name: 'Action' }, { id: 12, name: 'Adventure' }],
    popularity: 230.0,
    originalLanguage: 'en',
    runtime: 127,
    tagline: 'Villains aren\'t born. They\'re made.',
    status: 'Post Production',
    cast: [
      { id: 74569, name: 'Aaron Taylor-Johnson', character: 'Sergei Kravinoff / Kraven', profileUrl: null },
      { id: 934, name: 'Russell Crowe', character: 'Nikolai Kravinoff', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 917496,
    title: 'Beetlejuice Beetlejuice',
    originalTitle: 'Beetlejuice Beetlejuice',
    overview: 'After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia\'s life is turned upside down when her daughter opens the portal to the Afterlife.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/vhbQQdPnfLUxhdXhREITF5cYppT.jpg',
    rating: 7.2,
    voteCount: 1900,
    ...getRelativeDate(20),
    genreIds: [35, 14, 27],
    genres: ['Comedy', 'Fantasy', 'Horror'],
    genreObjects: [{ id: 35, name: 'Comedy' }, { id: 14, name: 'Fantasy' }],
    popularity: 290.0,
    originalLanguage: 'en',
    runtime: 104,
    tagline: 'The ghost with the most is back.',
    status: 'Post Production',
    cast: [
      { id: 2232, name: 'Michael Keaton', character: 'Beetlejuice', profileUrl: null },
      { id: 32, name: 'Winona Ryder', character: 'Lydia Deetz', profileUrl: null },
      { id: 1253391, name: 'Jenna Ortega', character: 'Astrid Deetz', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 1064213,
    title: 'Anora',
    originalTitle: 'Anora',
    overview: 'Anora, a young sex worker from Brooklyn, gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairy tale is threatened.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/cgXk2tNYhJZLXdBDO5DidAVzQ82.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
    rating: 8.0,
    voteCount: 1400,
    ...getRelativeDate(40),
    genreIds: [35, 18, 10749],
    genres: ['Comedy', 'Drama', 'Romance'],
    genreObjects: [{ id: 35, name: 'Comedy' }, { id: 18, name: 'Drama' }],
    popularity: 260.0,
    originalLanguage: 'en',
    runtime: 139,
    tagline: 'A love story with no rules.',
    status: 'Post Production',
    cast: [
      { id: 1253392, name: 'Mikey Madison', character: 'Anora / Ani', profileUrl: null },
      { id: 1253393, name: 'Mark Eydelshteyn', character: 'Vanya', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 933260,
    title: 'The Substance',
    originalTitle: 'The Substance',
    overview: 'A fading celebrity takes a black-market drug: a cell-replicating substance that temporarily creates a younger, better version of herself.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/vhbQQdPnfLUxhdXhREITF5cYppT.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    rating: 7.6,
    voteCount: 1700,
    ...getRelativeDate(15),
    genreIds: [18, 27, 878],
    genres: ['Drama', 'Horror', 'Science Fiction'],
    genreObjects: [{ id: 18, name: 'Drama' }, { id: 27, name: 'Horror' }],
    popularity: 270.0,
    originalLanguage: 'en',
    runtime: 141,
    tagline: 'If you respect the balance, what could go wrong?',
    status: 'Post Production',
    cast: [
      { id: 1253394, name: 'Demi Moore', character: 'Elisabeth Sparkle', profileUrl: null },
      { id: 1253395, name: 'Margaret Qualley', character: 'Sue', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  },
  {
    id: 1184918,
    title: 'The Wild Robot',
    originalTitle: 'The Wild Robot',
    overview: 'After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island and must learn to adapt to the harsh surroundings, gradually bonding with the island\'s animals.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/417tYZ4XUyJrtyZXj7HpvWf1E8f.jpg',
    rating: 8.4,
    voteCount: 2800,
    ...getRelativeDate(25),
    genreIds: [16, 878, 10751],
    genres: ['Animation', 'Science Fiction', 'Family'],
    genreObjects: [{ id: 16, name: 'Animation' }, { id: 878, name: 'Science Fiction' }],
    popularity: 330.0,
    originalLanguage: 'en',
    runtime: 102,
    tagline: 'Discover your true nature.',
    status: 'Post Production',
    cast: [
      { id: 1253371, name: 'Lupita Nyong\'o', character: 'Roz (voice)', profileUrl: null },
      { id: 1253381, name: 'Pedro Pascal', character: 'Fink (voice)', profileUrl: null }
    ],
    recommendations: [],
    similar: []
  }
];

// Unified catalog map for O(1) lookup and global search / details resolution
export const allCuratedMovies: MovieDetails[] = [
  ...fallbackTrending,
  ...fallbackPopular,
  ...fallbackTopRated,
  ...fallbackNowPlaying,
  ...fallbackUpcoming
];

// Deduplicate unified catalog so each ID has 1 master MovieDetails record
export const fallbackCatalogMap = new Map<number, MovieDetails>();
for (const movie of allCuratedMovies) {
  if (!fallbackCatalogMap.has(movie.id)) {
    fallbackCatalogMap.set(movie.id, movie);
  }
}
